Partial migration from Ant to Gradle
pybee/voc pull request #719
Opened 2018-01-01 11:10 UTC by drurenia

- I started with the easy tasks and migrated few tasks to Gradle: all, upload, checkstyle, clean;
- Added a test task as well to make it easier to execute it (not working because it lacks the venv as specified below);
- Upload and test (newly added) tasks are not working for now because a virtual env is needed to execute them. I haven't figured out yet how to achieve this on Gradle so any suggestion would be great;
- Added Gradle wrapper to eliminate the need for the installation; 
- Importing all remaining tasks from Ant automatically using ant.importBuild "build.xml", so everything still works fine using both ant and gradle commands;

2018-01-21 21:44 UTC, phildini commented
Hi there! Sorry for the long delay in feedaback. What would you suggest is the best way to test this? Can these be run locally easily?

2018-01-25 09:28 UTC, drurenia commented
Not a problem @phildini. Since we have a Gradle wrapper in place, you could easily test it using:
`./gradlew <task_name>`

Please bear in mind that I opened this pull request because @eliasdorneles asked me to but I don't think it is supposed so be merged yet. I think since it's my first contribution to this project he wanted to check whether I am going to the right direction or not.

2018-02-25 23:42 UTC, eliasdorneles requested changes
Hi @drurenia !
Sorry for the looong time to review -- I've been eyeing this PR for a while, but life happened! :)
So, I think this is a good start, but there is a few more things I'd hope to see before this is ready to be included -- ideally, at least we'd be able to do `./gradlew build` and it would compile all the Java stuff with Gradle.
I've made some comments below on some things that are not quite right.
How big of a task do you think it would be to move from Ant to Gradle completely?
Thank you!!

2018-02-25 23:42 UTC, eliasdorneles commented on build.gradle
> +task test(type: Exec) {
This target should be removed: besides the fact that this is hardcoding a virtualenv path, the gradle build config should concern only the Java resources, not the python stuff.

2018-02-25 23:42 UTC, eliasdorneles commented on build.xml
> -      <arg value="b${release}"/>
This argument seems to be missing in the Gradle version.

2020-04-25 02:30 UTC, phildini commented
Hi there! It looks like this PR might be dead, so we're closing it for now. Feel free to re-open it if you'd like to continue, or think about directing your efforts to https://github.com/beeware/briefcase or https://github.com/beeware/toga. Both of these have more active development right now. 😄

2020-04-25 02:30 UTC, closed without merging